// Code generated by protoc-gen-zig
///! package inspector_state
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
const ManagedStruct = protobuf.ManagedStruct;

pub const InspectorState = struct {
    actors: ArrayList(ActorSnapshot),
    inbox_throughput_metrics: ?InboxThroughputMetrics = null,

    pub const _desc_table = .{
        .actors = fd(1, .{ .List = .{ .SubMessage = {} } }),
        .inbox_throughput_metrics = fd(2, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ActorSnapshot = struct {
    id: ManagedString,
    actor_type_name: ManagedString,
    inbox_metrics: ?InboxMetrics = null,

    pub const _desc_table = .{
        .id = fd(1, .String),
        .actor_type_name = fd(2, .String),
        .inbox_metrics = fd(3, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const InboxMetrics = struct {
    envelope_count: i64 = 0,
    capacity: i64 = 0,
    last_message_at: i64 = 0,
    throughput_metrics: ?InboxThroughputMetrics = null,

    pub const _desc_table = .{
        .envelope_count = fd(1, .{ .Varint = .Simple }),
        .capacity = fd(2, .{ .Varint = .Simple }),
        .last_message_at = fd(3, .{ .Varint = .Simple }),
        .throughput_metrics = fd(4, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const InboxThroughputMetrics = struct {
    time: f64 = 0,
    delta_time: f32 = 0,
    envelope_counter: i32 = 0,
    previous_time: f64 = 0,
    refresh_time: f64 = 0,
    rolling_average_eps: f64 = 0,
    smoothing_factor: f64 = 0.1,

    pub const _desc_table = .{
        .time = fd(1, .{ .FixedInt = .I64 }),
        .delta_time = fd(2, .{ .FixedInt = .I32 }),
        .envelope_counter = fd(3, .{ .Varint = .Simple }),
        .previous_time = fd(4, .{ .FixedInt = .I64 }),
        .refresh_time = fd(5, .{ .FixedInt = .I64 }),
        .rolling_average_eps = fd(6, .{ .FixedInt = .I64 }),
        .smoothing_factor = fd(7, .{ .FixedInt = .I64 }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
