// Code generated by protoc-gen-zig
///! package inspector_state
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
const ManagedStruct = protobuf.ManagedStruct;

pub const InspectorState = struct {
    actors: ArrayList(ActorSnapshot),
    inbox_metrics: ?InboxMetrics = null,
    messages_per_second: f64 = 0,

    pub const _desc_table = .{
        .actors = fd(1, .{ .List = .{ .SubMessage = {} } }),
        .inbox_metrics = fd(2, .{ .SubMessage = {} }),
        .messages_per_second = fd(3, .{ .FixedInt = .I64 }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ActorSnapshot = struct {
    id: ManagedString,

    pub const _desc_table = .{
        .id = fd(1, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const InboxMetrics = struct {
    len: i64 = 0,
    capacity: i64 = 0,
    last_message_at: i64 = 0,
    messages_per_second: f64 = 0,

    pub const _desc_table = .{
        .len = fd(1, .{ .Varint = .Simple }),
        .capacity = fd(2, .{ .Varint = .Simple }),
        .last_message_at = fd(3, .{ .Varint = .Simple }),
        .messages_per_second = fd(4, .{ .FixedInt = .I64 }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
