// Code generated by protoc-gen-zig
///! package inspector_state
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
const ManagedStruct = protobuf.ManagedStruct;

pub const InspectorState = struct {
    actors: ArrayList(ActorSnapshot),

    pub const _desc_table = .{
        .actors = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ActorSnapshot = struct {
    id: ManagedString,

    pub const _desc_table = .{
        .id = fd(1, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
